### ISSUE TITLE
Have you considered adopting material theme builder css variable names?

### ISSUE THREAD

**Issue by juanpmarin** [CosmicMind/materialcss#4]
Material is publishing a set of tools that generates themes from an image or a set of colors:

- https://m3.material.io/theme-builder
- https://www.figma.com/community/plugin/1034969338659738588/Material-Theme-Builder
- https://github.com/material-foundation/material-color-utilities

And they all follow the same naming conventions for the CSS variables, it would be incredible that materialcss uses them so that the adoption is easier

For example I'm considering to migrate from [material-web](https://github.com/material-components/material-web) to materialcss

**Comment by daniel-jonathan** [comment]
@juanpmarin Hey! Actually, I already have a script that generates the themes from the Figma JSON output in Material Theme Builder. It is what I used to create the necessary light and dark theme files, [example theme](https://github.com/CosmicMind/materialcss/tree/release/src/themes). It takes in a directory of JSON files and outputs all the themes defined in the format that is in the example. If you visit [MaterialCss](http://materialcss.org), you can see the theme colors on the left side, which have all been generated using the script. 

I will create a discussion and share the script and details of how to generate the themes.

**Comment by juanpmarin** [comment]
That's awesome, thanks!
Is there a reason to not use those generated CSS variables directly instead of converting the names?

**Comment by daniel-jonathan** [comment]
The names I generate take the camelCase JSON and turn it into kebab-case in order to be CSS like. I'll look into the casing and adhere to that. Maybe I am using the wrong reference. This is a good one, thank you :) 

For the library [material-color-utilities](https://github.com/material-foundation/material-color-utilities), this is great. Instead of relying on scripts, it would be ideal to have a generator that uses the project you shared as a service through the site. This way it can demo the colors and avoid maintaining scripts. 

I am going to create the service over the weekend, and then add the update to this issue. At the moment, I pushed the additional CSS themes that I have on the site, and I look forward to your feedback for the service. 

I will leave this issue open until it is ready over the weekend.

**Comment by juanpmarin** [comment]
Have you tried to export the theme as CSS instead of json? When you export as CSS, variables are generated following a structure that material web components understand, look:
```
:root {
 --md-sys-color-primary: var(--md-sys-color-primary-dark);
 --md-sys-color-on-primary: var(--md-sys-color-on-primary-dark);
 --md-sys-color-primary-container: var(--md-sys-color-primary-container-dark);
 --md-sys-color-on-primary-container: var(--md-sys-color-on-primary-container-dark);
 --md-sys-color-secondary: var(--md-sys-color-secondary-dark);
 --md-sys-color-on-secondary: var(--md-sys-color-on-secondary-dark);
 --md-sys-color-secondary-container: var(--md-sys-color-secondary-container-dark);
 --md-sys-color-on-secondary-container: var(--md-sys-color-on-secondary-container-dark);
 --md-sys-color-tertiary: var(--md-sys-color-tertiary-dark);
 --md-sys-color-on-tertiary: var(--md-sys-color-on-tertiary-dark);
 --md-sys-color-tertiary-container: var(--md-sys-color-tertiary-container-dark);
 --md-sys-color-on-tertiary-container: var(--md-sys-color-on-tertiary-container-dark);
 --md-sys-color-error: var(--md-sys-color-error-dark);
 --md-sys-color-on-error: var(--md-sys-color-on-error-dark);
 --md-sys-color-error-container: var(--md-sys-color-error-container-dark);
 --md-sys-color-on-error-container: var(--md-sys-color-on-error-container-dark);
 --md-sys-color-outline: var(--md-sys-color-outline-dark);
 --md-sys-color-background: var(--md-sys-color-background-dark);
 --md-sys-color-on-background: var(--md-sys-color-on-background-dark);
 --md-sys-color-surface: var(--md-sys-color-surface-dark);
 --md-sys-color-on-surface: var(--md-sys-color-on-surface-dark);
 --md-sys-color-surface-variant: var(--md-sys-color-surface-variant-dark);
 --md-sys-color-on-surface-variant: var(--md-sys-color-on-surface-variant-dark);
 --md-sys-color-inverse-surface: var(--md-sys-color-inverse-surface-dark);
 --md-sys-color-inverse-on-surface: var(--md-sys-color-inverse-on-surface-dark);
 --md-sys-color-inverse-primary: var(--md-sys-color-inverse-primary-dark);
 --md-sys-color-shadow: var(--md-sys-color-shadow-dark);
 --md-sys-color-surface-tint: var(--md-sys-color-surface-tint-dark);
 --md-sys-color-outline-variant: var(--md-sys-color-outline-variant-dark);
 --md-sys-color-scrim: var(--md-sys-color-scrim-dark);
}
```

You can export it to CSS with this option:
![image](https://github.com/CosmicMind/materialcss/assets/13415603/541faa33-515d-495d-b949-86c52f9b4a6c)
![image](https://github.com/CosmicMind/materialcss/assets/13415603/ebf0a27b-58b0-4759-b5f7-f78a519b0949)

https://m3.material.io/theme-builder#/custom

The figma plugin can also export as CSS.

**Comment by daniel-jonathan** [comment]
Great! This is much easier, and yet I will still make the theming tool. I like the idea of having the entire site convert to a theme generated so that people can see how every component is affected. I do think that following the same CSS naming is ideal to make this framework compatible with other core tools. 

I will make an update now, your timing is great on this suggestion.

**Comment by juanpmarin** [comment]
That's great man! Thank you for being open to suggestions

By the way, the ability to change the theme at runtime in the docs sounds awesome

**Comment by daniel-jonathan** [comment]
Thank you! I enjoy working with others, so hopefully many suggestions that help make this project awesome will come this repos way :) 

That said, now the naming uses the `--md-sys-colo-` prefix. I recommend if you want to support multiple themes, a parent theme and scheme., otherwise, the variables will take effect when defined, like in the `:root` css value. 

```sass
.odyssey
  &.theme-light
    --md-sys-color-primary: #{$primary-rgb}
    --md-sys-color-on-primary: #{$on-primary-rgb}
    --md-sys-color-primary-container: #{$primary-container-rgb}
    --md-sys-color-on-primary-container: #{$on-primary-container-rgb}
    --md-sys-color-primary-fixed: #{$primary-fixed-rgb}
    --md-sys-color-on-primary-fixed: #{$on-primary-fixed-rgb}
    --md-sys-color-primary-fixed-dim: #{$primary-fixed-dim-rgb}
    --md-sys-color-on-primary-fixed-variant: #{$on-primary-fixed-variant-rgb}
    --md-sys-color-secondary: #{$secondary-rgb}
    --md-sys-color-on-secondary: #{$on-secondary-rgb}
    --md-sys-color-secondary-container: #{$secondary-container-rgb}
    --md-sys-color-on-secondary-container: #{$on-secondary-container-rgb}
    --md-sys-color-secondary-fixed: #{$secondary-fixed-rgb}
    --md-sys-color-on-secondary-fixed: #{$on-secondary-fixed-rgb}
    --md-sys-color-secondary-fixed-dim: #{$secondary-fixed-dim-rgb}
    --md-sys-color-on-secondary-fixed-variant: #{$on-secondary-fixed-variant-rgb}
    --md-sys-color-tertiary: #{$tertiary-rgb}
    --md-sys-color-on-tertiary: #{$on-tertiary-rgb}
    --md-sys-color-tertiary-container: #{$tertiary-container-rgb}
    --md-sys-color-on-tertiary-container: #{$on-tertiary-container-rgb}
    --md-sys-color-tertiary-fixed: #{$tertiary-fixed-rgb}
    --md-sys-color-on-tertiary-fixed: #{$on-tertiary-fixed-rgb}
    --md-sys-color-tertiary-fixed-dim: #{$tertiary-fixed-dim-rgb}
    --md-sys-color-on-tertiary-fixed-variant: #{$on-tertiary-fixed-variant-rgb}
    --md-sys-color-error: #{$error-rgb}
    --md-sys-color-error-container: #{$error-container-rgb}
    --md-sys-color-on-error: #{$on-error-rgb}
    --md-sys-color-on-error-container: #{$on-error-container-rgb}
    --md-sys-color-background: #{$background-rgb}
    --md-sys-color-on-background: #{$on-background-rgb}
    --md-sys-color-outline: #{$outline-rgb}
    --md-sys-color-inverse-on-surface: #{$inverse-on-surface-rgb}
    --md-sys-color-inverse-surface: #{$inverse-surface-rgb}
    --md-sys-color-inverse-primary: #{$inverse-primary-rgb}
    --md-sys-color-shadow: #{$shadow-rgb}
    --md-sys-color-surface-tint: #{$surface-tint-rgb}
    --md-sys-color-outline-variant: #{$outline-variant-rgb}
    --md-sys-color-scrim: #{$scrim-rgb}
    --md-sys-color-surface: #{$surface-rgb}
    --md-sys-color-on-surface: #{$on-surface-rgb}
    --md-sys-color-surface-variant: #{$surface-variant-rgb}
    --md-sys-color-on-surface-variant: #{$on-surface-variant-rgb}
    --md-sys-color-surface-container-highest: #{$surface-container-highest-rgb}
    --md-sys-color-surface-container-high: #{$surface-container-high-rgb}
    --md-sys-color-surface-container: #{$surface-container-rgb}
    --md-sys-color-surface-container-low: #{$surface-container-low-rgb}
    --md-sys-color-surface-container-lowest: #{$surface-container-lowest-rgb}
    --md-sys-color-surface-dim: #{$surface-dim-rgb}
    --md-sys-color-surface-bright: #{$surface-bright-rgb}
```
