### ISSUE TITLE
Icon is not importing selection

### ISSUE THREAD

**Issue by juanpmarin** [CosmicMind/materialcss#5]
Icon is using `%is-not-selectable` but it's not importing selection, so icon file can't be compiled alone

https://github.com/CosmicMind/materialcss/blob/1a2bcaf151cb4f4a44df158f197dede169d77b90/src/lib/_icon.sass#L34

**Comment by daniel-jonathan** [comment]
@juanpmarin thank you for sharing this issue. I will fix it up tonight and go through the other files as well.

**Comment by daniel-jonathan** [comment]
@juanpmarin Apologies for the delay, Please find an update for this issue in the [latest release](https://github.com/CosmicMind/materialcss/pkgs/npm/materialcss/100385269);

If there is a further issue with imports, please feel free to reopen or create a new issue. Thank you!
